# Generated by Django 2.2.8 on 2020-01-30 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_blacklist', '0007_auto_20171017_2214'),
        ('products', '0006_auto_20200130_1701'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
