# Generated by Django 2.2.7 on 2019-11-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_userproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='mealtime',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('supper', 'Supper')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='userproduct',
            unique_together={('product', 'date', 'mealtime')},
        ),
    ]
