# Generated by Django 2.2.7 on 2019-11-29 11:56
import csv
import os
from itertools import islice

from django.db import migrations, transaction

from fitit import settings
from products.models import Product


def insert_products(apps, schema_editor):
    with open(os.path.join(
            settings.BASE_DIR, "products/migrations/products.csv")
    ) as csvfile:
        reader = csv.DictReader(csvfile)
        products = (Product(**row) for row in reader)
        batch_size = 100
        while True:
            batch = list(islice(products, batch_size))
            if not batch:
                break
            with transaction.atomic():
                Product.objects.bulk_create(batch, batch_size)


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0003_auto_20191128_2359'),
    ]

    operations = [
        migrations.RunPython(insert_products),
    ]
